pipeline {
    agent any
    
    environment {
        NEXUS_CREDENTIALS = credentials('nexus-credentials-id')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/yourusername/yourrepository.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install -Dmaven.test.skip=true'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQubeServer') {
                    sh 'mvn sonar:sonar'
                }
            }
        }

        stage('Deploy') {
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'https',
                    nexusUrl: 'https://nexus.example.com',
                    groupId: 'com.example',
                    version: '1.0.0',
                    repository: 'maven-snapshots',
                    credentialsId: "${NEXUS_CREDENTIALS}",
                    artifacts: [
                        [artifactId: 'your-artifact', file: 'target/your-artifact-1.0.0.jar']
                    ]
                )
            }
        }
    }
}
