pipeline {
    agent any
    
    environment {
        NEXUS_CREDENTIALS = credentials('nexus-credentials-id')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/ravurumanoj/simple-java-maven-app.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install -Dmaven.test.skip=true'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQubeServer') {
                    sh 'mvn sonar:sonar'
                }
            }
        }

        stage('Deploy') {
            steps {
                def pom = readMavenPom file: 'pom.xml'                
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'https',
                    nexusUrl: 'http://52.91.128.112:8081/#admin/repository/repositories:maven-snapshot',
                    groupId: pom.groupId,
                    version: pom.version,
                    repository: 'maven-snapshot',
                    credentialsId: "${NEXUS_CREDENTIALS}",
                    artifacts: [
                        [artifactId: pom.artifactId, file: "target/${pom.artifactId}-${pom.version}.jar",
                            type: 'jar']
                    ]
                )
            }
        }
    }
}
